# Generated by Django 6.0.3 on 2026-03-20 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('icon', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
