# Generated by Django 6.0.3 on 2026-03-21 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_day', models.PositiveSmallIntegerField()),
                ('rollover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.category')),
            ],
            options={
                'ordering': ['category__name', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('category', 'account'), name='unique_budget_category_account'), models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('category',), name='unique_budget_category_global')],
            },
        ),
    ]
